import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Organic Avocados',
    price: 4.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'organic avocados',
    description: 'Pack of 4 creamy, organic Hass avocados.',
    longDescription: 'Our organic Hass avocados are grown in nutrient-rich soil without synthetic pesticides. They are known for their creamy texture and rich, nutty flavor. Perfect for toast, salads, or guacamole.',
  },
  {
    id: '2',
    name: 'Fresh Strawberries',
    price: 3.49,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'fresh strawberries',
    description: '1 lb of sweet, juicy strawberries.',
    longDescription: 'Hand-picked at peak ripeness, our strawberries are bursting with sweet, natural flavor. They are a great source of Vitamin C and antioxidants. Enjoy them fresh, in desserts, or as a healthy snack.',
  },
  {
    id: '3',
    name: 'Artisanal Sourdough',
    price: 5.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'sourdough bread',
    description: 'A freshly baked loaf of artisanal sourdough bread.',
    longDescription: 'Baked daily using a traditional starter, our sourdough has a delightful tangy flavor, a chewy crumb, and a perfectly crisp crust. It\'s made with organic flour and contains no preservatives.',
  },
  {
    id: '4',
    name: 'Free-Range Eggs',
    price: 6.29,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'free-range eggs',
    description: 'One dozen large brown free-range eggs.',
    longDescription: 'Our hens are free to roam on open pastures, resulting in eggs with rich, flavorful yolks. These free-range eggs are a testament to our commitment to ethical and sustainable farming.',
  },
  {
    id: '5',
    name: 'Heirloom Tomatoes',
    price: 4.79,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'heirloom tomatoes',
    description: 'A mix of colorful and flavorful heirloom tomatoes.',
    longDescription: 'Experience the vibrant colors and diverse flavors of our heirloom tomatoes. Grown from seeds passed down through generations, each variety offers a unique taste, from sweet to tangy. Perfect for salads and sauces.',
  },
  {
    id: '6',
    name: 'Cold-Pressed Olive Oil',
    price: 12.99,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'olive oil',
    description: '500ml bottle of extra virgin cold-pressed olive oil.',
    longDescription: 'Our extra virgin olive oil is cold-pressed from the finest olives to preserve its natural antioxidants and robust, fruity flavor. It\'s perfect for dressings, dipping, or finishing your favorite dishes.',
  },
];
